services:
  auth-service:
    build: ./auth-service
    container_name: auth-service
    ports:
      - "4000:4000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/authdb
      - JWT_SECRET=your_super_secret_key
    depends_on:
      - mongo
    volumes:
      - ./auth-service:/app
    networks:
      - insta-net

  mongo:
    image: mongo:6
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - insta-net

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"   # RabbitMQ main port
      - "15672:15672" # RabbitMQ management UI
    networks:
      - insta-net

volumes:
  mongo-data:

networks:
  insta-net: